GET http://localhost:8080/produtos/?categoria=Eletro
Content-Type: application/json

GET http://localhost:8080/produtos/?nome=LG
Content-Type: application/json

GET http://localhost:8080/produtos/
Content-Type: application/json

POST http://localhost:8080/produtos/
Content-Type: application/json

{
    "nome": "Irmãos Karamazov",
	"descricao": "Livro Irmãos Karamazov",
	"preco": "80.0",
	"categoriaId": 5
}

PATCH http://localhost:8080/produtos/6
Content-Type: application/json

{
	"descricao": "Livro Irmãos Karamazov 2ª edição",
	"preco": "95.0"
}

DELETE  http://localhost:8080/produtos/6