version: '3.3'
services:
    mysqlsrv:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "MySql2019!"
            MYSQL_DATABASE: "ecommerce-produtos"
        ports:
        - "3306:3306"
        volumes:
        - /home/paulo/Desenvolvimento/docker/mysql:/var/lib/mysql
        networks:
        - broker-kafka
    
networks: 
  broker-kafka:
    driver: bridge  